// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABcsIFsU-0Dl1CrZbnukdmRBVxYuBOjkk',
    appId: '1:511156072895:web:10947962f2116b3fafb10a',
    messagingSenderId: '511156072895',
    projectId: 'retropressapp',
    authDomain: 'retropressapp.firebaseapp.com',
    storageBucket: 'retropressapp.firebasestorage.app',
    measurementId: 'G-VD9M0B63GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMXduAme2eL8hACUJulaApoo_maVKpcU',
    appId: '1:511156072895:android:ec049446ede7da56afb10a',
    messagingSenderId: '511156072895',
    projectId: 'retropressapp',
    storageBucket: 'retropressapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9dY1GkM3NkRCBhZhqbmYWyJb45AMh9E',
    appId: '1:511156072895:ios:954dbb4e8f6075aaafb10a',
    messagingSenderId: '511156072895',
    projectId: 'retropressapp',
    storageBucket: 'retropressapp.firebasestorage.app',
    iosBundleId: 'com.example.retroPressAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ9dY1GkM3NkRCBhZhqbmYWyJb45AMh9E',
    appId: '1:511156072895:ios:954dbb4e8f6075aaafb10a',
    messagingSenderId: '511156072895',
    projectId: 'retropressapp',
    storageBucket: 'retropressapp.firebasestorage.app',
    iosBundleId: 'com.example.retroPressAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABcsIFsU-0Dl1CrZbnukdmRBVxYuBOjkk',
    appId: '1:511156072895:web:f59463a79c9f2966afb10a',
    messagingSenderId: '511156072895',
    projectId: 'retropressapp',
    authDomain: 'retropressapp.firebaseapp.com',
    storageBucket: 'retropressapp.firebasestorage.app',
    measurementId: 'G-G1R755MMSG',
  );
}
